-- CreateTable
CREATE TABLE "SiteContent" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "photo" TEXT NOT NULL,
    "bio" TEXT NOT NULL,
    "shortBio" TEXT NOT NULL,
    "yearsExperience" INTEGER NOT NULL,
    "insuredCount" INTEGER NOT NULL,
    "satisfactionScore" REAL NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "website" TEXT NOT NULL,
    "address" TEXT,
    "whatsappNumber" TEXT NOT NULL,
    "whatsappMessage" TEXT NOT NULL,
    "calculatorTitle" TEXT,
    "calculatorDesc" TEXT,
    "faqPreviewTitle" TEXT,
    "referralTitle" TEXT,
    "referralDesc" TEXT,
    "updatedAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
